name: Build and Test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}  # macos-latest, windows-latest https://help.github.com/en/articles/virtual-environments-for-github-actions
    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest, macos-latest
    steps:
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout source code
        uses: actions/checkout@v1   # checked out to /home/work/<repo name>, can overwrite with path arg

      - name: Staticcheck
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Build
        env:
          GOPOXY: "https://proxy.golang.org"
        run: go build cmd/mailer/mailer.go

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: home/work/mailer  # path to upload from i.e. /home/work/<binary>